blank_issues_enabled: false
contact_links:
  - name: "Chore"
    url: "/issues/new?template=âš™chore-template.md"
    about: "ì¼ë°˜ì ì¸ ì‘ì—…ì„ ê¸°ë¡í•˜ëŠ” í…œí”Œë¦¿ì…ë‹ˆë‹¤."
  - name: "Other"
    url: "/issues/new?template=ğŸ¨other-template.md"
    about: "ê¸°íƒ€ ì‘ì—…ì„ ê¸°ë¡í•˜ëŠ” í…œí”Œë¦¿ì…ë‹ˆë‹¤."
  - name: "Fix"
    url: "/issues/new?template=ğŸ”§fix-template.md"
    about: "ë²„ê·¸ ìˆ˜ì •ê³¼ ê´€ë ¨ëœ ì´ìŠˆë¥¼ ê¸°ë¡í•˜ëŠ” í…œí”Œë¦¿ì…ë‹ˆë‹¤."
  - name: "Feature"
    url: "/issues/new?template=ğŸ› feature-template.md"
    about: "ìƒˆë¡œìš´ ê¸°ëŠ¥ ì¶”ê°€ì™€ ê´€ë ¨ëœ ì´ìŠˆë¥¼ ê¸°ë¡í•˜ëŠ” í…œí”Œë¦¿ì…ë‹ˆë‹¤."
